# Spring Application Name
spring.application.name=vehicle-rental-marketplace

# Server Port
server.port=8080

# Active Spring Profile: Choose 'h2' for zero-setup in-memory database with H2 Console, or 'mysql' for local MySQL database.
spring.profiles.active=mysql
#spring.profiles.active=h2

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Static Resources
spring.web.resources.static-locations=classpath:/static/
